## **Numpy**
----------



### **Dimensions and Shape Of an Array**

##### **1) 32** - Scalar, 0Dimensional
##### **2) [1,2]** -1Dimensional
##### **3) [[1,2],[2,6]]** -2Dimensional

In [5]:
array1 = np.array(32)
array2 = np.array([1,2])
array3 = np.array([[1,2],[2,6]])

In [8]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

0
1
2


In [9]:
array1 = np.array([])
array2 = np.array([[]])
array3 = np.array([[[]]])

In [10]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
3


---------

### **Create Array**

#### **Method 0: By Using List or Tuple**

In [2]:
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [3]:
array1 = np.array((1,2,3,4,5))
array1

array([1, 2, 3, 4, 5])

In [4]:
array1 = np.array([1,2,3,4,5],dtype='float')
array1

array([1., 2., 3., 4., 5.])

In [2]:
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [2]:
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

#### **Method 1: Using arange**

In [11]:
array1 = np.arange(1,10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
array1 = np.arange(1,10,2)
array1

array([1, 3, 5, 7, 9])

#### **Method 2: Using linspace**

In [16]:
array1 = np.linspace(0,10)
array1

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
array1 = np.linspace(0,10,4)
array1

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

#### **Method 3: Array With all elements are Zero**

In [19]:
array1 = np.zeros(5)
array1

array([0., 0., 0., 0., 0.])

In [20]:
array2 = np.zeros([2,4])
array2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
array2 = np.zeros([2,4],dtype="int")
array2

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#### **Method 4: Array With all elements are Ones**

In [22]:
array1 = np.ones(5)
array1

array([1., 1., 1., 1., 1.])

In [24]:
array1 = np.ones([7,6],dtype="int")
array1

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

#### **Method 5: Array Full of Any Value**

In [26]:
array1 = np.full(5,8)
array1

array([8, 8, 8, 8, 8])

In [27]:
array1 = np.full([2,6],8)
array1

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [28]:
array1 = np.full([2,6],6.7)
array1

array([[6.7, 6.7, 6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7, 6.7, 6.7]])

#### **Method 6: Random Floats Between 0 to 1 - Based on Given Number How Much You Want**

In [36]:
array1 = np.random.rand(10)
array1

array([0.31257336, 0.62588048, 0.1113093 , 0.49147779, 0.94089409,
       0.05200627, 0.72680887, 0.97585428, 0.42178215, 0.58754642])

In [35]:
array1 = np.random.rand(2,2)
array1

array([[0.29258267, 0.79830164],
       [0.9752543 , 0.37986269]])

#### **Method 7: Random Integers**

In [43]:
array1 = np.random.randint(1,100)
array1

17

In [4]:
array1 = np.random.randint(1,100,size=(2,2))
array1

array([[ 2, 48],
       [86, 73]])

#### **Method 8: Random Selection**

In [7]:
arr = [10, 20, 30, 40, 50]
np.random.choice(arr)  

50

In [21]:
arr = [10, 20, 30, 40, 50]
np.random.choice(arr, size=3)  

array([20, 20, 10])

In [18]:
arr = [10, 20, 30, 40, 50,60,70,80,90,100]
np.random.choice(arr, size=5, replace=True) ## Duplicates Are Allowed

array([ 50, 100,  90, 100,  80])

In [22]:
arr = [10, 20, 30, 40, 50,60,70,80,90,100]
np.random.choice(arr, size=5, replace=False) ## Duplicates Are Not Allowed

array([ 60, 100,  80,  40,  10])

#### **Method 9: Shuffling and Permutations**

In [25]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)                             #  Shuffle array in-place


[3 1 5 2 4]


In [27]:
arr = np.array([1, 2, 3, 4, 5])
shuffled = np.random.permutation(arr)
print(arr)                             #    Get a shuffled copy (original remains the same)

[1 2 3 4 5]


### **Aggregate Functions**

In [29]:
# Calculates the total sum of values.
a = np.array([1,2,4])
b = np.array([[10,20],[20,40]])
print(np.sum(a))
print(np.sum(b))

7
90


In [30]:
# Returns the average (mean)
print(np.mean(a))
print(np.mean(b))

2.3333333333333335
22.5


In [31]:
# Find the smallest / largest value.
print(np.max(a))
print(np.max(b))

print(np.min(a))
print(np.min(b))

4
40
1
10


In [32]:
# Returns the middle value.
print(np.median(a))
print(np.median(b))

2.0
20.0


In [25]:
# Standard deviation (how spread out data is).
print(np.std(a))
print(np.std(b))

1.247219128924647
10.897247358851684


In [26]:
# Get the value at a specific percentile.
print(np.percentile(a, 75))

3.0


In [27]:
# Cumulative sum: Running totals over time.
print(np.cumsum(a))
print(np.cumsum(b))

[1 3 7]
[10 30 50 90]


In [28]:
# Index (position) of min or max value.
print(np.argmin(a))
print(np.argmax(b))

0
3


#### **Method 10: Random Seed (Reproducibility)**

In [28]:
np.random.seed(42)                      #    Using a seed ensures you get the same results every time you run the code.

In [33]:
# Usage of Seed

import numpy as np
print(np.random.randint(1, 10, 5))      #    Gives Different Results EveyTime

[3 7 8 5 4]


In [34]:
import numpy as np

np.random.seed(42)
print(np.random.randint(1, 10, 5))      #    Gives Same Results EveyTime

[7 4 8 5 7]


### **Element Wise Operation**

In [2]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)          # [11 22 33]
print("Subtraction:", a - b)       # [ 9 18 27]
print("Multiplication:", a * b)    # [10 40 90]
print("Division:", a / b)          # [10. 10. 10.]
print("Power:", a ** b)            # [10 400 27000]
print("Modulus:", a % b)           # [0 0 0]

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]
Power: [   10   400 27000]
Modulus: [0 0 0]


In [3]:
## Scalar

a = np.array([1, 2, 3])
print(a + 10)  # [11 12 13]
print(a * 5)   # [ 5 10 15]

[11 12 13]
[ 5 10 15]


In [6]:
## Element Wise On 2D Arrays

a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])

print(a + b)
print(a * b)

[[11 22]
 [33 44]]
[[ 10  40]
 [ 90 160]]


----------------

### **Array Attributes**

In [11]:
a = np.array([10,20])
b = np.array([[10,20],[60,70]])

#### **.shape**

In [12]:
print(a.shape)
print(b.shape)

(2,)
(2, 2)


#### **.size**

In [13]:
print(a.size)
print(b.size)

2
4


#### **.dtype**

In [14]:
print(a.dtype)
print(b.dtype)

int32
int32


#### **.ndim**

In [16]:
print(a.ndim)
print(b.ndim)

1
2


### **Advanced Manipulations**

#### **.reshape**

In [5]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)  # Reshape into 2 rows and 3 columns

In [6]:
b = np.array([10,20,30,40]).reshape(4,1)
b

array([[10],
       [20],
       [30],
       [40]])

In [7]:
b = np.arange(1,21).reshape(4,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

#### **.flatten**

In [13]:
array1 = np.array([10,20,40,50,60])
array1.flatten()

array([10, 20, 40, 50, 60])

In [15]:
array1 = np.array([[10,20],[40,50],[60,70]])
array1.flatten()

array([10, 20, 40, 50, 60, 70])

In [16]:
array1 = np.array([[[10,20],[40,50],[60,70]]])
array1.flatten()

array([10, 20, 40, 50, 60, 70])

#### **.ravel**

In [25]:
array1 = np.array([10,20,30,40])
array1.ravel()

array([10, 20, 30, 40])

In [28]:
array1 = np.array([[10,20],[30,40]])
array1.ravel()

array([10, 20, 30, 40])

In [29]:
array1 = np.array([[[10,20],[30,40]]])
array1.ravel()

array([10, 20, 30, 40])

#### **.transpose**

In [61]:
a = np.array([[1, 2], [3, 4]])
b = a.transpose()
b

array([[1, 3],
       [2, 4]])

In [62]:
a = np.array([[[1, 2], [3, 4],[5,6]]])
b = a.transpose()
b

array([[[1],
        [3],
        [5]],

       [[2],
        [4],
        [6]]])

---------------


### **Universal Functions**

#### **1) np.sqrt() – Square root**

In [66]:
import numpy as np

a = np.array([4, 9, 16])
b = np.sqrt(a)
print(b)

[2. 3. 4.]


In [70]:
a = 36
b = np.sqrt(a)
b

6.0

#### **2) np.exp() – Exponential (eˣ)**

In [75]:
a = np.array([1, 2, 3])
b = np.exp(a)
print(b)  # [ 2.71828183  7.3890561  20.08553692 ]

[ 2.71828183  7.3890561  20.08553692]


#### **3) np.log() – Natural logarithm (log base e)**

In [76]:
a = np.array([1, np.e, np.e**2])
b = np.log(a)
print(b)  # [0. 1. 2.]

[0. 1. 2.]


#### **4) np.sin() – Sine (in radians)**

In [77]:
a = np.array([0, np.pi/2, np.pi])
b = np.sin(a)
print(b)  # [0. 1. 0.]

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


#### **5) np.round() – Round to nearest whole number**

In [104]:
a = np.array([1.2, 2.5, 3.8])
b = np.round(a)
print(b)  # [1. 2. 4.]

[1. 2. 4.]


----------

### **Set Operations**

#### **np.unique()**

In [79]:
import numpy as np

a = np.array([1, 2, 2, 3, 3, 3])
result = np.unique(a)
print(result)  # [1 2 3]

[1 2 3]


In [83]:
b = np.array([[1,2,3,4],[2,3,5,6]])
result = np.unique(b)
result

array([1, 2, 3, 4, 5, 6])

#### **np.intersect1d()**

In [99]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

result = np.intersect1d(a, b)
print(result)  

[2 3]


In [102]:
a = np.array([[1, 2, 5, 6, 7, 8]])
b = np.array([2, 3, 4, 6 , 7])

result = np.intersect1d(a, b)
print(result)  

[2 6 7]


In [103]:
a = np.array([[1, 2, 5, 6, 7, 8]])
b = np.array([[2, 3, 4, 6 , 7]])

result = np.intersect1d(a, b)
print(result)  

[2 6 7]


#### **np.union1d()**

In [87]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

result = np.union1d(a, b)
print(result)  # [1 2 3 4 5]

[1 2 3 4 5]


In [91]:
a = np.array([[1, 2, 3],[4,5,6]])
b = np.array([3, 4, 5])

result = np.union1d(a, b)
print(result) 

[1 2 3 4 5 6]


In [92]:
a = np.array([[1, 2, 3],[4,5,6]])
b = np.array([[3, 4, 5],[7,8,9]])

result = np.union1d(a, b)
print(result) 

[1 2 3 4 5 6 7 8 9]


----------

### **Numpy Data Types and Type Casting**

In [45]:
array1 = np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [46]:
array1 = np.array([1,2,3.2,4])
array1

array([1. , 2. , 3.2, 4. ])

In [49]:
lst = ["string",1,2,6.7]
array = np.array(lst)
print(array)
print(array.dtype)

['string' '1' '2' '6.7']
<U32


In [52]:
array1 = np.array([1,2,4],dtype="float64")
print(array1)
print(array1.dtype)

[1. 2. 4.]
float64


In [53]:
array1 = np.array([1.2,2.2,4],dtype="int64")
print(array1)
print(array1.dtype)

[1 2 4]
int64


-----------

### **Type Casting: Using astype()**

In [57]:
array1 = np.array([1,2,4])
print(array1)
new_array = array1.astype('float64')
print(new_array)

[1 2 4]
[1. 2. 4.]


---------

### **Arithmetic Operations on Arrays**

In [33]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [34]:
# Addition
print(array1+array2)
print(np.add(array1,array2))

[5 7 9]
[5 7 9]


In [35]:
# Subtraction
print(array1-array2)
print(np.subtract(array1,array2))

[-3 -3 -3]
[-3 -3 -3]


In [37]:
# Multiplication
print(array1*array2)
print(np.multiply(array1,array2))

[ 4 10 18]
[ 4 10 18]


In [39]:
# Division
print(array1/array2)
print(np.divide(array1,array2))

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


In [41]:
# Integer Division
print(array1//array2)

[0 0 0]


In [75]:
# Modulus
print(array2%array1)

[0 1 0]


In [76]:
# Exponent --> Power
print(array1**2)

[1 4 9]


---------------------
### **Universal Functions**

In [77]:
print(np.sqrt(array1))

[1.         1.41421356 1.73205081]


In [79]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


-----------------

### **Indexing and Slicing**

In [80]:
array1 = np.array([1,2,4,5,6,7,8,9,10])

In [81]:
array1[0]

1

In [82]:
array1[-1]

10

In [83]:
array1[0:4]

array([1, 2, 4, 5])

In [84]:
array1[0:4:2]

array([1, 4])

In [85]:
array1[-1:-4:-1]

array([10,  9,  8])

In [87]:
array1[-1::-2]

array([10,  8,  6,  4,  1])

In [88]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0:2])

[[1 2 3]
 [4 5 6]]


In [89]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0:2,:1])

[[1]
 [4]]


#### **Transpose**

In [90]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


----------------

### **Stacking**
#### **Concatenation - vstack and hstack**

#### **vstack**

In [31]:
array1 = np.array([10, 20, 30, 40])
array2 = np.array([40, 50, 60, 70])
array3 = np.vstack((array1, array2))
print(array3)

[[10 20 30 40]
 [40 50 60 70]]


In [34]:
array1 = np.array([[10, 20, 30, 40],[50,60,70,80]])
array2 = np.array([40, 50, 60, 70])
array3 = np.vstack((array1, array2))
print(array3)

[[10 20 30 40]
 [50 60 70 80]
 [40 50 60 70]]


In [35]:
array1 = np.array([[10, 20, 30, 40],[50,60,70,80]])
array2 = np.array([[40, 50, 60, 70]])
array3 = np.vstack((array1, array2))
print(array3)

[[10 20 30 40]
 [50 60 70 80]
 [40 50 60 70]]


#### **.hstack**

In [40]:
array1 = np.array([1,2])
array2 = np.array([3,4])
new_array = np.hstack([array1,array2])
new_array

array([1, 2, 3, 4])

In [41]:
array1 = np.array([1,2,3,4])
array2 = np.array([3,4])
new_array = np.hstack([array1,array2])
new_array

array([1, 2, 3, 4, 3, 4])

In [42]:
array1 = np.array([[1,2],[4,5]])
array2 = np.array([[3,4],[5,6]])
new_array = np.hstack([array1,array2])
new_array

array([[1, 2, 3, 4],
       [4, 5, 5, 6]])



#### **Splitting Of an Array**

In [49]:
a = np.array([10, 20, 30, 40, 50, 60])
result = np.split(a, 3)
result

[array([10, 20]), array([30, 40]), array([50, 60])]

In [50]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
result = np.split(a, 2, axis=1)  # Split along columns
result

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

--------
### **Repeating**
- It Repeats Each Element 

In [9]:
array1 = np.array([1,2,4])
print(np.repeat(array1,2))

[1 1 2 2 4 4]


In [10]:
print(np.repeat(array1,4))

[1 1 1 1 2 2 2 2 4 4 4 4]


### **tile**

- It Repeats Whole Array

In [11]:
print(np.tile(array1,2))

[1 2 4 1 2 4]


In [12]:
print(np.repeat(array1,4))

[1 1 1 1 2 2 2 2 4 4 4 4]


-----

### **Aggregate Functions**
- It is Used to Summarize the array.

In [13]:
array1 = np.array([[1,2,3,4,5,6],
                   [7,8,9,10,11,12],
                   [13,14,15,16,17,18],
                   [19,20,21,22,23,24],
                   [25,26,27,28,29,30],
                   [31,32,33,34,35,36]])
array1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [14]:
print(np.sum(array1))

666


In [15]:
# Average
print(np.mean(array1))

18.5


In [16]:
print(np.median(array1))

18.5


In [17]:
print(np.std(array1))

10.388294694831615


In [18]:
print(np.var(array1))

107.91666666666667


In [19]:
print(np.min(array1))

1


In [20]:
print(np.max(array1))

36


In [22]:
# Row Wise Sum
print(np.sum(array1,axis=0))

[ 96 102 108 114 120 126]


In [23]:
# Column Wise Sum
print(np.sum(array1,axis=1))

[ 21  57  93 129 165 201]


----------
### **Cumulative Operations**
- These are used to calculate running total.

In [24]:
array1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [25]:
print(np.cumsum(array1))

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210 231 253 276 300 325 351 378 406 435 465 496 528 561 595 630 666]


In [26]:
print(np.cumprod(array1))

[          1           2           6          24         120         720
        5040       40320      362880     3628800    39916800   479001600
  1932053504  1278945280  2004310016  2004189184  -288522240  -898433024
   109641728 -2102132736 -1195114496  -522715136   862453760  -775946240
  2076180480 -1853882368  1484783616 -1375731712 -1241513984  1409286144
   738197504 -2147483648 -2147483648           0           0           0]


-----------
### **Conditional Based Choices**

In [35]:
array = np.array([[1,2],[10,20]])

In [36]:
# Where

In [37]:
result = np.where(array1<10,"low","high")
result

array([['low', 'low', 'low', 'low', 'low', 'low'],
       ['low', 'low', 'low', 'high', 'high', 'high'],
       ['high', 'high', 'high', 'high', 'high', 'high'],
       ['high', 'high', 'high', 'high', 'high', 'high'],
       ['high', 'high', 'high', 'high', 'high', 'high'],
       ['high', 'high', 'high', 'high', 'high', 'high']], dtype='<U4')

In [38]:
# For Value That are greater than 15 and less than 35
result1 = np.logical_and(array1>15,array1<35)
result1

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False]])

In [40]:
print(np.argwhere(array>5))

[[1 0]
 [1 1]]


In [42]:
# For Value That are greater than 15 or less than 35
result1 = np.logical_or(array1>15,array1>20)
result1

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

----------

### **BroadCasting**
- It means stretching the smaller array to match the shape of the bigger array
- Numpy compares the shapes of the arrays from the end (right to left) and follow these rules:
#### **Rules**
**1.** If Shapes are equal they are compatible.</br>
**2.** If one is 1, It can be stretched to match the other.</br>
**3.** If shapes are different Not 1 or equal --> Error

In [44]:
array1 = np.array([[100,200],[400,600]])
array2 = array1 + 50

In [47]:
print(array2)
print(array2.shape)

[[150 250]
 [450 650]]
(2, 2)


#### **Example 1: Add scalar to array**

In [17]:
import numpy as np
a = np.array([1, 2, 3])
b = 5
print(a + b)
# Here, b is a scalar. It is broadcast to [5, 5, 5].

[6 7 8]


#### **Example2: 1D with 2D Array**

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2, 3)
B = np.array([10, 20, 30])           # shape (3,)
print(A + B)  # shape becomes (2, 3)

[[11 22 33]
 [14 25 36]]


In [19]:
A = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])  # shape (2, 3)
B = np.array([10, 20, 30])           # shape (3,)
print(A + B)  # shape becomes (2, 3)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
#### ****

-------------------

### **Vectorization**
- Replacing Loops operations with single function
- np.vectorize() --> Convert a regular function to be applied on an array.

**It is Used**
- When you apply a custom function to every element
- For readability
- It is not faster than loop
- It only makes syntax cleaner, but doesnot improve speed like real vectorized numpy functions.

In [48]:
def square(x):
    return x*x
vfunc = np.vectorize(square)

In [50]:
vfunc(array1)

array([[ 10000,  40000],
       [160000, 360000]])

-----------
### **Handling Missing Values**


In [51]:
array1 = np.array([1,2,np.nan,4])
array1

array([ 1.,  2., nan,  4.])

In [52]:
# np.inf and -np.inf --> Represents Positive and Negative Infinites

In [53]:
array1 = np.array([1,2,np.inf,4])
array1

array([ 1.,  2., inf,  4.])

In [54]:
# np.isnan
# np.isinf
# np.isinfinite

# These are Functions Used to detect any null values, finite or infinite values

In [55]:
array1 = np.array([1,2,np.nan,4])
np.isnan(array1)

array([False, False,  True, False])

In [60]:
array2 = np.array([1,2,np.inf,4])
np.isinf(array2)

array([False, False,  True, False])

In [61]:
array4 = np.nan_to_num(array1)
array4

array([ 1.00000000e+000,  2.00000000e+000, -1.79769313e+308,
        4.00000000e+000])

----------

### **Matrix Operations**

#### **1) dot()**

In [17]:
array1 = np.array([[1,2,3]])  # (1,3)
array2 = np.array([[4],[5],[6]])  # (3,1)
result = np.dot(array1,array2)  # (1,1)
print(result)

[[32]]


In [18]:
array1 = np.array([[1,2],[4,5],[6,7]])   # (3,2)
array2 = np.array([[1,2,3,4],[5,6,7,8]]) # (2,3)
result = np.dot(array1,array2)  # (3,3)
print(result)

[[11 14 17 20]
 [29 38 47 56]
 [41 54 67 80]]


#### **2) transpose()**

In [20]:
array1 = np.array([[1,2,4],[6,7,9]])
print(np.transpose(array1))

[[1 6]
 [2 7]
 [4 9]]


----------------

### **Solving Linear Equation Using np.linalg.solve()**

`````python
Example: 2x + y = 8
         3x + 2y = 13

In [22]:
array1 = np.array([[2,1],[3,2]])
array2 = np.array([8,13])

print(np.linalg.solve(array1,array2))  # x = 3. y = 2.

[3. 2.]


------------------

### **File I/O Operations**

#### **1) np.save()**

In [23]:
array1 = np.array([[1,2,4],[6,7,9]])
np.save('Hello.npy',array1)

#### **2) np.load()**

In [26]:
loaded = np.load('Hello.npy')
loaded

array([[1, 2, 4],
       [6, 7, 9]])

#### **3) np.loadtxt**

````python
data = np.loadtxt('data.txt')    # Default: Space Delimeter
data = np.loadtxt('data.txt',delimter = ',')    # For CSV File 

----------------

### **Handling Missing Values**

#### **1) np.isnan()**

In [28]:
array1 = np.array([[1,2,np.nan,4]])
print(np.isnan(array1))

[[False False  True False]]


In [29]:
array1 = np.array([1,2,np.nan,4])
print(np.isnan(array1))

[False False  True False]


#### **2) np.nan_to_num()**

In [30]:
array1 = np.array([[1,2,np.nan,4]])
print(np.nan_to_num(array1,nan=0))

[[1. 2. 0. 4.]]


In [31]:
array1 = np.array([[1,2,np.nan,4],[np.nan,6,7,9]])
print(np.nan_to_num(array1,nan=0))

[[1. 2. 0. 4.]
 [0. 6. 7. 9.]]


------------------

### **Broad Casting**

In [1]:
import numpy as np

In [9]:
array1 = np.array(6)
array2 = np.array([1,2,4])
array1+array2

array([ 7,  8, 10])

In [13]:
array1 = np.array(6)
array2 = np.array([[1,2,4],[6,7,8]]) 
array1 + array2

array([[ 7,  8, 10],
       [12, 13, 14]])

(3,)
(2, 3)
